services:
  app1:
    build:
      context: .
    image: express-server
    container_name: express-server-1
    expose:
      - "8000"

  app2:
    build:
      context: .
    image: express-server
    container_name: express-server-2
    expose:
      - "8000"

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
